title: "Physics PhD Portfolio"
email: axa1253@case.edu
description: >-
  Personal academic website of an experimental physicist
baseurl: ""
url: "https://aneesha6.github.io"
theme: minima
plugins:
  - jekyll-feed
